# ETL Step 1 — Extract: Load Raw Lightcast Data

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/lightcast_2024.csv", low_memory=False)

In [2]:
print("Shape:", df.shape)

Shape: (72498, 131)

In [3]:
df.columns.tolist()

['ID',
 'LAST_UPDATED_DATE',
 'LAST_UPDATED_TIMESTAMP',
 'DUPLICATES',
 'POSTED',
 'EXPIRED',
 'DURATION',
 'SOURCE_TYPES',
 'SOURCES',
 'URL',
 'ACTIVE_URLS',
 'ACTIVE_SOURCES_INFO',
 'TITLE_RAW',
 'BODY',
 'MODELED_EXPIRED',
 'MODELED_DURATION',
 'COMPANY',
 'COMPANY_NAME',
 'COMPANY_RAW',
 'COMPANY_IS_STAFFING',
 'EDUCATION_LEVELS',
 'EDUCATION_LEVELS_NAME',
 'MIN_EDULEVELS',
 'MIN_EDULEVELS_NAME',
 'MAX_EDULEVELS',
 'MAX_EDULEVELS_NAME',
 'EMPLOYMENT_TYPE',
 'EMPLOYMENT_TYPE_NAME',
 'MIN_YEARS_EXPERIENCE',
 'MAX_YEARS_EXPERIENCE',
 'IS_INTERNSHIP',
 'SALARY',
 'REMOTE_TYPE',
 'REMOTE_TYPE_NAME',
 'ORIGINAL_PAY_PERIOD',
 'SALARY_TO',
 'SALARY_FROM',
 'LOCATION',
 'CITY',
 'CITY_NAME',
 'COUNTY',
 'COUNTY_NAME',
 'MSA',
 'MSA_NAME',
 'STATE',
 'STATE_NAME',
 'COUNTY_OUTGOING',
 'COUNTY_NAME_OUTGOING',
 'COUNTY_INCOMING',
 'COUNTY_NAME_INCOMING',
 'MSA_OUTGOING',
 'MSA_NAME_OUTGOING',
 'MSA_INCOMING',
 'MSA_NAME_INCOMING',
 'NAICS2',
 'NAICS2_NAME',
 'NAICS3',
 'NAICS3_NAME',
 'NAICS4',
 'NAICS4_NAME',
 'NAICS5',
 'NAICS5_NAME',
 'NAICS6',
 'NAICS6_NAME',
 'TITLE',
 'TITLE_NAME',
 'TITLE_CLEAN',
 'SKILLS',
 'SKILLS_NAME',
 'SPECIALIZED_SKILLS',
 'SPECIALIZED_SKILLS_NAME',
 'CERTIFICATIONS',
 'CERTIFICATIONS_NAME',
 'COMMON_SKILLS',
 'COMMON_SKILLS_NAME',
 'SOFTWARE_SKILLS',
 'SOFTWARE_SKILLS_NAME',
 'ONET',
 'ONET_NAME',
 'ONET_2019',
 'ONET_2019_NAME',
 'CIP6',
 'CIP6_NAME',
 'CIP4',
 'CIP4_NAME',
 'CIP2',
 'CIP2_NAME',
 'SOC_2021_2',
 'SOC_2021_2_NAME',
 'SOC_2021_3',
 'SOC_2021_3_NAME',
 'SOC_2021_4',
 'SOC_2021_4_NAME',
 'SOC_2021_5',
 'SOC_2021_5_NAME',
 'LOT_CAREER_AREA',
 'LOT_CAREER_AREA_NAME',
 'LOT_OCCUPATION',
 'LOT_OCCUPATION_NAME',
 'LOT_SPECIALIZED_OCCUPATION',
 'LOT_SPECIALIZED_OCCUPATION_NAME',
 'LOT_OCCUPATION_GROUP',
 'LOT_OCCUPATION_GROUP_NAME',
 'LOT_V6_SPECIALIZED_OCCUPATION',
 'LOT_V6_SPECIALIZED_OCCUPATION_NAME',
 'LOT_V6_OCCUPATION',
 'LOT_V6_OCCUPATION_NAME',
 'LOT_V6_OCCUPATION_GROUP',
 'LOT_V6_OCCUPATION_GROUP_NAME',
 'LOT_V6_CAREER_AREA',
 'LOT_V6_CAREER_AREA_NAME',
 'SOC_2',
 'SOC_2_NAME',
 'SOC_3',
 'SOC_3_NAME',
 'SOC_4',
 'SOC_4_NAME',
 'SOC_5',
 'SOC_5_NAME',
 'LIGHTCAST_SECTORS',
 'LIGHTCAST_SECTORS_NAME',
 'NAICS_2022_2',
 'NAICS_2022_2_NAME',
 'NAICS_2022_3',
 'NAICS_2022_3_NAME',
 'NAICS_2022_4',
 'NAICS_2022_4_NAME',
 'NAICS_2022_5',
 'NAICS_2022_5_NAME',
 'NAICS_2022_6',
 'NAICS_2022_6_NAME']

In [4]:
df.dtypes

ID                            str
LAST_UPDATED_DATE             str
LAST_UPDATED_TIMESTAMP        str
DUPLICATES                float64
POSTED                        str
                           ...
NAICS_2022_4_NAME             str
NAICS_2022_5              float64
NAICS_2022_5_NAME             str
NAICS_2022_6              float64
NAICS_2022_6_NAME             str
Length: 131, dtype: object

In [5]:
pd.set_option('display.max_columns', None)
df.head(5)

,ID,LAST_UPDATED_DATE,LAST_UPDATED_TIMESTAMP,DUPLICATES,POSTED,EXPIRED,DURATION,SOURCE_TYPES,SOURCES,URL,ACTIVE_URLS,ACTIVE_SOURCES_INFO,TITLE_RAW,BODY,MODELED_EXPIRED,MODELED_DURATION,COMPANY,COMPANY_NAME,COMPANY_RAW,COMPANY_IS_STAFFING,EDUCATION_LEVELS,EDUCATION_LEVELS_NAME,MIN_EDULEVELS,MIN_EDULEVELS_NAME,MAX_EDULEVELS,MAX_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,MIN_YEARS_EXPERIENCE,MAX_YEARS_EXPERIENCE,IS_INTERNSHIP,SALARY,REMOTE_TYPE,REMOTE_TYPE_NAME,ORIGINAL_PAY_PERIOD,SALARY_TO,SALARY_FROM,LOCATION,CITY,CITY_NAME,COUNTY,COUNTY_NAME,MSA,MSA_NAME,STATE,STATE_NAME,COUNTY_OUTGOING,COUNTY_NAME_OUTGOING,COUNTY_INCOMING,COUNTY_NAME_INCOMING,MSA_OUTGOING,MSA_NAME_OUTGOING,MSA_INCOMING,MSA_NAME_INCOMING,NAICS2,NAICS2_NAME,NAICS3,NAICS3_NAME,NAICS4,NAICS4_NAME,NAICS5,NAICS5_NAME,NAICS6,NAICS6_NAME,TITLE,TITLE_NAME,TITLE_CLEAN,SKILLS,SKILLS_NAME,SPECIALIZED_SKILLS,SPECIALIZED_SKILLS_NAME,CERTIFICATIONS,CERTIFICATIONS_NAME,COMMON_SKILLS,COMMON_SKILLS_NAME,SOFTWARE_SKILLS,SOFTWARE_SKILLS_NAME,ONET,ONET_NAME,ONET_2019,ONET_2019_NAME,CIP6,CIP6_NAME,CIP4,CIP4_NAME,CIP2,CIP2_NAME,SOC_2021_2,SOC_2021_2_NAME,SOC_2021_3,SOC_2021_3_NAME,SOC_2021_4,SOC_2021_4_NAME,SOC_2021_5,SOC_2021_5_NAME,LOT_CAREER_AREA,LOT_CAREER_AREA_NAME,LOT_OCCUPATION,LOT_OCCUPATION_NAME,LOT_SPECIALIZED_OCCUPATION,LOT_SPECIALIZED_OCCUPATION_NAME,LOT_OCCUPATION_GROUP,LOT_OCCUPATION_GROUP_NAME,LOT_V6_SPECIALIZED_OCCUPATION,LOT_V6_SPECIALIZED_OCCUPATION_NAME,LOT_V6_OCCUPATION,LOT_V6_OCCUPATION_NAME,LOT_V6_OCCUPATION_GROUP,LOT_V6_OCCUPATION_GROUP_NAME,LOT_V6_CAREER_AREA,LOT_V6_CAREER_AREA_NAME,SOC_2,SOC_2_NAME,SOC_3,SOC_3_NAME,SOC_4,SOC_4_NAME,SOC_5,SOC_5_NAME,LIGHTCAST_SECTORS,LIGHTCAST_SECTORS_NAME,NAICS_2022_2,NAICS_2022_2_NAME,NAICS_2022_3,NAICS_2022_3_NAME,NAICS_2022_4,NAICS_2022_4_NAME,NAICS_2022_5,NAICS_2022_5_NAME,NAICS_2022_6,NAICS_2022_6_NAME
0,1f57d95acf4dc67ed2819eb12f049f6a5c11782c,9/6/2024,2024-09-06 20:32:57.352 Z,0.0,6/2/2024,6/8/2024,6.0,"[\n ""Company""\n]","[\n ""brassring.com""\n]","[\n ""https://sjobs.brassring.com/TGnewUI/Sear...",[],NaN,Enterprise Analyst (II-III),31-May-2024\n\nEnterprise Analyst (II-III)\n\n...,6/8/2024,6.0,894731.0,Murphy USA,Murphy USA,False,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),2.0,2.0,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 33.20763,\n ""lon"": -92.6662674\n}",RWwgRG9yYWRvLCBBUg==,"El Dorado, AR",5139.0,"Union, AR",20980.0,"El Dorado, AR",5.0,Arkansas,5139.0,"Union, AR",5139.0,"Union, AR",20980.0,"El Dorado, AR",20980.0,"El Dorado, AR",44.0,Retail Trade,441.0,Motor Vehicle and Parts Dealers,4413.0,"Automotive Parts, Accessories, and Tire Retailers",44133.0,Automotive Parts and Accessories Retailers,441330.0,Automotive Parts and Accessories Retailers,ET29C073C03D1F86B4,Enterprise Analysts,enterprise analyst ii iii,"[\n ""KS126DB6T061MHD7RTGQ"",\n ""KS126706DPFD3...","[\n ""Merchandising"",\n ""Mathematics"",\n ""Pr...","[\n ""KS126DB6T061MHD7RTGQ"",\n ""KS128006L3V0H...","[\n ""Merchandising"",\n ""Predictive Modeling""...",[],[],"[\n ""KS126706DPFD3354M7YK"",\n ""KS1280B68GD79...","[\n ""Mathematics"",\n ""Presentations"",\n ""Re...","[\n ""KS440W865GC4VRBW6LJP"",\n ""KS13USA80NE38...","[\n ""SQL (Programming Language)"",\n ""Power B...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""45.0601"",\n ""27.0101""\n]","[\n ""Economics, General"",\n ""Mathematics, Ge...","[\n ""45.06"",\n ""27.01""\n]","[\n ""Economics"",\n ""Mathematics""\n]","[\n ""45"",\n ""27""\n]","[\n ""Social Sciences"",\n ""Mathematics and St...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101011.0,General ERP Analyst / Consultant,2310.0,Business Intelligence,23101011.0,General ERP Analyst / Consultant,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,[\n 7\n],"[\n ""Artificial Intelligence""\n]",44.0,Retail Trade,441.0,Motor Vehicle and Parts Dealers,4413.0,"Automotive Parts, Accessories, and Tire Retailers",44133.0,Automotive Parts and Accessories Retailers,441330.0,Automotive Parts and Accessories Retailers
1,0cb072af26757b6c4ea9464472a50a443af681ac,8/2/2024,2024-08-02 17:08:58.838 Z,0.0,6/2/2024,8/1/2024,NaN,"[\n ""Job Board""\n]","[\n ""maine.gov""\n]","[\n ""https://joblink.maine.gov/jobs/1085740""\n]",[],NaN,Oracle Consultant - Reports (3592),Oracle Consultant - Reports (3592)\n\nat SMX i...,8/1/2024,NaN,133098.0,Smx Corporation Limited,SMX,True,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,1.0,Full-time (> 32 hours),3.0,3.0,False,NaN,1.0,Remote,NaN,NaN,NaN,"{\n ""lat"": 44.3106241,\n ""lon"": -69.7794897\n}",QXVndXN0YSwgTUU=,"Augusta, ME",23011.0,"Kennebec, ME",12300.0,"Augusta-Waterville, ME",23.0,Maine,23011.0,"Kennebec, ME",23011.0,"Kennebec, ME",12300.0,"Augusta-Waterville, ME",12300.0,"Augusta-Waterville, ME",56.0,Administrative and Support and Waste Managemen...,561.0,Administrative and Support Services,5613.0,Employment Services,56132.0,Temporary Help Services,561320.0,Temporary Help Services,ET21DDA63780A7DC09,Oracle Consultants,oracle consultant reports,"[\n ""KS122626T550SLQ7QZ1C"",\n ""KS123YJ6KVWC9...","[\n ""Procurement"",\n ""Financial Statements"",...","[\n ""KS122626T550SLQ7QZ1C"",\n ""KS123YJ6KVWC9...","[\n ""Procurement"",\n ""Financial Statements"",...",[],[],[],[],"[\n ""BGSBF3F508F7F46312E3"",\n ""ESEA839CED378...","[\n ""Oracle Business Intelligence (BI) / OBIA...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101012.0,Oracle Consultant / Analyst,2310.0,Business Intelligence,23101012.0,Oracle Consultant / Analyst,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,56.0,Administrative and Support and Waste Managemen...,561.0,Administrative and Support Services,5613.0,Employment Services,56132.0,Temporary Help Services,561320.0,Temporary Help Services
2,85318b12b3331fa490d32ad014379df01855c557,9/6/2024,2024-09-06 20:32:57.352 Z,1.0,6/2/2024,7/7/2024,35.0,"[\n ""Job Board""\n]","[\n ""dejobs.org""\n]","[\n ""https://dejobs.org/dallas-tx/data-analys...",[],NaN,Data Analyst,Taking care of people is at the heart of every...,6/10/2024,8.0,39063746.0,Sedgwick,Sedgwick,False,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),5.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 32.7766642,\n ""lon"": -96.7969879\n}",RGFsbGFzLCBUWA==,"Dallas, TX",48113.0,"Dallas, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",48.0,Texas,48113.0,"Dallas, TX",48113.0,"Dallas, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",52.0,Finance and Insurance,524.0,Insurance Carriers and Related Activities,5242.0,"Agencies, Brokerages, and Other Insurance Rela...",52429.0,Other Insurance Related Activities,524291.0,Claims Adjusting,ET3037E0C947A02404,Data Analysts,data analyst,"[\n ""KS1218W78FGVPVP2KXPX"",\n ""ESF3939CE1F80...","[\n ""Management"",\n ""Exception Reporting"",\n...","[\n ""ESF3939CE1F80C10C327"",\n ""KS120GV6C72JM...","[\n ""Exception Reporting"",\n ""Data Analysis""...","[\n ""KS683TN76T77DQDVBZ1B""\n]","[\n ""Security Clearance""\n]","[\n ""KS1218W78FGVPVP2KXPX"",\n ""BGS1ADAA36DB6...","[\n ""Management"",\n ""Report Writing"",\n ""In...","[\n ""KS126HY6YLTB9R7XJC4Z""\n]","[\n ""Microsoft Office""\n]",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231113.0,Data / Data Mining Analyst,23111310.0,Data Analyst,2311.0,Data Analysis and Mathematics,23111310.0,Data Analyst,231113.0,Data / Data Mining Analyst,2311.0,Data Analysis and Mathematics,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,52.0,Finance and Insurance,524.0,Insurance Carriers and Related Activities,5242.0,"Agencies, Brokerages, and Other Insurance Rela...",52429.0,Other Insurance Related Activities,524291.0,Claims Adjusting
3,1b5c3941e54a1889ef4f8ae55b401a550708a310,9/6/2024,2024-09-06 20:32:57.352 Z,1.0,6/2/2024,7/20/2024,48.0,"[\n ""Job Board""\n]","[\n ""disabledperson.com"",\n ""dejobs.org""\n]","[\n ""https://www.disabledperson.com/jobs/5948...",[],NaN,Sr. Lead Data Mgmt. Analyst - SAS Product Owner,About this role:\n\nWells Fargo is looking for...,6/12/2024,10.0,37615159.0,Wells Fargo,Wells Fargo,False,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,1.0,Full-time (> 32 hours),3.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 33.4483771,\n ""lon"": -112.0740373\n}",UGhvZW5peCwgQVo=,"Phoenix, AZ",4013.0,"Maricopa, AZ",38060.0,"Phoenix-Mesa-Chandler, AZ",4.0,Arizona,4013.0,"Maricopa, AZ",4013.0,"Maricopa, AZ",38060.0,"Phoenix-Mesa-Chandler, AZ",38060.0,"Phoenix-Mesa-Chandler, AZ",52.0,Finance and Insurance,522.0,Credit Intermediation and Related Activities,5221.0,Depository Credit Intermediation,52211.0,Commercial Banking,522110.0,Commercial Banking,ET2114E0404BA30075,Management Analysts,sr lead data mgmt analyst sas product owner,"[\n ""KS123QX62QYTC4JF38H8"",\n ""KS7G6NP6R6L1H...","[\n ""Exit Strategies"",\n ""Reliability"",\n ""...","[\n ""KS123QX62QYTC4JF38H8"",\n ""KS441PQ64HT13...","[\n ""Exit Strategies"",\n ""User Story"",\n ""H...",[],[],"[\n ""KS7G6NP6R6L1H1SKFTSY"",\n ""KS1218W78FGVP...","[\n ""Reliability"",\n ""Management"",\n ""Strat...","[\n ""KS4409D76NW1S5LNCL18"",\n ""ESC7869CF7378...","[\n ""SAS (Software)"",\n ""Google Cloud Platfo...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231113.0,Data / Data Mining Analyst,23111310.0,Data Analyst,2311.0,Data Analysis and Mathematics,23111310.0,Data Analyst,231113.0,Data / Data Mining Analyst,2311.0,Data Analysis and Mathematics,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,[\n 6\n],"[\n ""Data Privacy/Protection""\n]",52.0,Finance and Insurance,522.0,Credit Intermediation and Related Activities,5221.0,Depository Credit Intermediation,52211.0,Commercial Banking,522110.0,Commercial Banking
4,cb5ca25f02bdf25c13edfede7931508bfd9e858f,6/19/2024,2024-06-19 07:00:00.000 Z,0.0,6/2/2024,6/17/2024,15.0,"[\n ""FreeJobBoard""\n]","[\n ""craigslist.org""\n]","[\n ""https://modesto.craigslist.org/sls/77475...",[],NaN,Comisiones de $1000 - $3000 por semana... Comi...,Comisiones de $1000 - $3000 por semana... Comi...,6/17/2024,15.0,0.0,Unclassified,LH/GM,False,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,3.0,Part-time / full-time,NaN,NaN,False,92500.0,0.0,[None],year,150000.0,35000.0,"{\n ""lat"": 37.6392595,\n ""lon"": -120.9970014\n}",TW9kZXN0bywgQ0E=,"Modesto, CA",6099.0,"Stanislaus, CA",33700.0,"Modesto, CA",6.0,California,6099.0,"Stanislaus, CA",6099.0,"Stanislaus, CA",33700.0,"Modesto, CA",33700.0,"Modesto, CA",99.0,Unclassified Industry,999.0,Unclassified Industry,9999.0,Unclassified Industry,99999.0,Unclassified Industry,999999.0,Unclassified Industry,ET0000000000000000,Unclassified,comisiones de por semana comiensa rapido,[],[],[],[],[],[],[],[],[],[],15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,[],[],[],[],[],[],15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101012.0,Oracle Consultant / Analyst,2310.0,Business Intelligence,23101012.0,Oracle Consultant / Analyst,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,99.0,Unclassified Industry,999.0,Unclassified Industry,9999.0,Unclassified Industry,99999.0,Unclassified Industry,999999.0,Unclassified Industry

In [6]:
df.tail()

,ID,LAST_UPDATED_DATE,LAST_UPDATED_TIMESTAMP,DUPLICATES,POSTED,EXPIRED,DURATION,SOURCE_TYPES,SOURCES,URL,ACTIVE_URLS,ACTIVE_SOURCES_INFO,TITLE_RAW,BODY,MODELED_EXPIRED,MODELED_DURATION,COMPANY,COMPANY_NAME,COMPANY_RAW,COMPANY_IS_STAFFING,EDUCATION_LEVELS,EDUCATION_LEVELS_NAME,MIN_EDULEVELS,MIN_EDULEVELS_NAME,MAX_EDULEVELS,MAX_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,MIN_YEARS_EXPERIENCE,MAX_YEARS_EXPERIENCE,IS_INTERNSHIP,SALARY,REMOTE_TYPE,REMOTE_TYPE_NAME,ORIGINAL_PAY_PERIOD,SALARY_TO,SALARY_FROM,LOCATION,CITY,CITY_NAME,COUNTY,COUNTY_NAME,MSA,MSA_NAME,STATE,STATE_NAME,COUNTY_OUTGOING,COUNTY_NAME_OUTGOING,COUNTY_INCOMING,COUNTY_NAME_INCOMING,MSA_OUTGOING,MSA_NAME_OUTGOING,MSA_INCOMING,MSA_NAME_INCOMING,NAICS2,NAICS2_NAME,NAICS3,NAICS3_NAME,NAICS4,NAICS4_NAME,NAICS5,NAICS5_NAME,NAICS6,NAICS6_NAME,TITLE,TITLE_NAME,TITLE_CLEAN,SKILLS,SKILLS_NAME,SPECIALIZED_SKILLS,SPECIALIZED_SKILLS_NAME,CERTIFICATIONS,CERTIFICATIONS_NAME,COMMON_SKILLS,COMMON_SKILLS_NAME,SOFTWARE_SKILLS,SOFTWARE_SKILLS_NAME,ONET,ONET_NAME,ONET_2019,ONET_2019_NAME,CIP6,CIP6_NAME,CIP4,CIP4_NAME,CIP2,CIP2_NAME,SOC_2021_2,SOC_2021_2_NAME,SOC_2021_3,SOC_2021_3_NAME,SOC_2021_4,SOC_2021_4_NAME,SOC_2021_5,SOC_2021_5_NAME,LOT_CAREER_AREA,LOT_CAREER_AREA_NAME,LOT_OCCUPATION,LOT_OCCUPATION_NAME,LOT_SPECIALIZED_OCCUPATION,LOT_SPECIALIZED_OCCUPATION_NAME,LOT_OCCUPATION_GROUP,LOT_OCCUPATION_GROUP_NAME,LOT_V6_SPECIALIZED_OCCUPATION,LOT_V6_SPECIALIZED_OCCUPATION_NAME,LOT_V6_OCCUPATION,LOT_V6_OCCUPATION_NAME,LOT_V6_OCCUPATION_GROUP,LOT_V6_OCCUPATION_GROUP_NAME,LOT_V6_CAREER_AREA,LOT_V6_CAREER_AREA_NAME,SOC_2,SOC_2_NAME,SOC_3,SOC_3_NAME,SOC_4,SOC_4_NAME,SOC_5,SOC_5_NAME,LIGHTCAST_SECTORS,LIGHTCAST_SECTORS_NAME,NAICS_2022_2,NAICS_2022_2_NAME,NAICS_2022_3,NAICS_2022_3_NAME,NAICS_2022_4,NAICS_2022_4_NAME,NAICS_2022_5,NAICS_2022_5_NAME,NAICS_2022_6,NAICS_2022_6_NAME
72493,4c25b449c876d8e22d3e356f368cde5ab525cd03,9/6/2024,2024-09-06 20:32:57.352 Z,0.0,8/16/2024,8/31/2024,15.0,"[\n ""Job Board""\n]","[\n ""dejobs.org""\n]","[\n ""https://dejobs.org/richmond-va/data-anal...",[],NaN,Data Analyst,TEKsystems\n\n \n \n \n\n \n\n \nData Analyst\...,8/31/2024,15.0,37110815.0,TEKsystems,TEKsystems,False,[\n 99\n],"[\n ""No Education Listed""\n]",99.0,No Education Listed,NaN,NaN,1.0,Full-time (> 32 hours),3.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 37.5407246,\n ""lon"": -77.4360481\n}",UmljaG1vbmQsIFZB,"Richmond, VA",51041.0,"Chesterfield, VA",40060.0,"Richmond, VA",51.0,Virginia,51041.0,"Chesterfield, VA",51760.0,"Richmond City, VA",40060.0,"Richmond, VA",40060.0,"Richmond, VA",54.0,"Professional, Scientific, and Technical Services",541.0,"Professional, Scientific, and Technical Services",5415.0,Computer Systems Design and Related Services,54151.0,Computer Systems Design and Related Services,541511.0,Custom Computer Programming Services,ET3037E0C947A02404,Data Analysts,data analyst,"[\n ""KS1282N6NQMZ95M1HJ7L"",\n ""KS13USA80NE38...","[\n ""Scrum (Software Development)"",\n ""Power...","[\n ""KS1282N6NQMZ95M1HJ7L"",\n ""KS13USA80NE38...","[\n ""Scrum (Software Development)"",\n ""Power...",[],[],"[\n ""KS1259D6L30YYG3XR3VL"",\n ""KS122556LMQ82...","[\n ""Interpersonal Communications"",\n ""Commu...","[\n ""KS13USA80NE38XJHA2TL"",\n ""KS125LS6N7WP4...","[\n ""Power BI"",\n ""Python (Programming Langu...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""52.0101""\n]","[\n ""Business/Commerce, General""\n]","[\n ""52.01""\n]","[\n ""Business/Commerce, General""\n]","[\n ""52""\n]","[\n ""Business, Management, Marketing, and Rel...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231113.0,Data / Data Mining Analyst,23111310.0,Data Analyst,2311.0,Data Analysis and Mathematics,23111310.0,Data Analyst,231113.0,Data / Data Mining Analyst,2311.0,Data Analysis and Mathematics,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,[\n 7\n],"[\n ""Artificial Intelligence""\n]",54.0,"Professional, Scientific, and Technical Services",541.0,"Professional, Scientific, and Technical Services",5415.0,Computer Systems Design and Related Services,54151.0,Computer Systems Design and Related Services,541511.0,Custom Computer Programming Services
72494,241d30b5478c0b1715618e0cfac65d40f781c0d8,10/21/2024,2024-10-21 13:59:53.998 Z,6.0,8/16/2024,NaN,NaN,"[\n ""Company"",\n ""Job Board""\n]","[\n ""myworkdayjobs.com"",\n ""mass-veterans.jo...","[\n ""https://wk.wd3.myworkdayjobs.com/en-us/e...","[\n ""https://wk.wd3.myworkdayjobs.com/en-US/E...","[\n {\n ""source"": ""jobserve.com"",\n ""ty...",Lead Enterprise Architect - SalesForce,Lead Enterprise Architect - SalesForce \nLead ...,9/13/2024,28.0,59335641.0,Wolters Kluwer,Wolters Kluwer N.V.,False,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),10.0,NaN,False,169275.0,0.0,[None],year,197550.0,141000.0,"{\n ""lat"": 42.3764852,\n ""lon"": -71.2356113\n}",V2FsdGhhbSwgTUE=,"Waltham, MA",25017.0,"Middlesex, MA",14460.0,"Boston-Cambridge-Newton, MA-NH",25.0,Massachusetts,25017.0,"Middlesex, MA",25017.0,"Middlesex, MA",14460.0,"Boston-Cambridge-Newton, MA-NH",14460.0,"Boston-Cambridge-Newton, MA-NH",51.0,Information,513.0,Publishing Industries,5131.0,"Newspaper, Periodical, Book, and Directory Pub...",51313.0,Book Publishers,513130.0,Book Publishers,ETA6C910340E81639B,Lead Enterprise Architects,lead enterprise architect salesforce,"[\n ""KS4407N6CMTCYT0NYSVM"",\n ""ESF6784E14B18...","[\n ""Salesforce"",\n ""Programming Languages"",...","[\n ""KS4407N6CMTCYT0NYSVM"",\n ""ESF6784E14B18...","[\n ""Salesforce"",\n ""Programming Languages"",...",[],[],"[\n ""KS441VC75P5WHX8QL5SN"",\n ""ES20CECA4FF83...","[\n ""Visionary"",\n ""Influencing Skills"",\n ...","[\n ""KS4407N6CMTCYT0NYSVM"",\n ""ESE9117F9A17C...","[\n ""Salesforce"",\n ""Salesforce Object Searc...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""52.0201"",\n ""11.0701""\n]","[\n ""Business Administration and Management, ...","[\n ""52.02"",\n ""11.07""\n]","[\n ""Business Administration, Management and ...","[\n ""52"",\n ""11""\n]","[\n ""Business, Management, Marketing, and Rel...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231510.0,Computer Systems Engineer / Architect,23151012.0,Enterprise Architect,2315.0,Network and Systems Engineering,23151012.0,Enterprise Architect,231510.0,Computer Systems Engineer / Architect,2315.0,Network and Systems Engineering,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,[\n 5\n],"[\n ""Cybersecurity""\n]",51.0,Information,513.0,Publishing Industries,5131.0,"Newspaper, Periodical, Book, and Directory Pub...",51313.0,Book Publishers,513130.0,Book Publishers
72495,3a0bc8e830dfb4ea44f721fb3139f41f398bb66d,10/16/2024,2024-10-16 13:45:59.907 Z,4.0,8/16/2024,9/22/2024,37.0,"[\n ""Job Board"",\n ""Company""\n]","[\n ""disabledperson.com"",\n ""dejobs.org""\n]","[\n ""https://disabilities.dejobs.org/lansing-...",[],NaN,Data Analyst,Volt\n\n \n \n \n\n \n\n \nData Analyst\n in\n...,8/31/2024,15.0,36997534.0,Volt,Volt,True,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),NaN,NaN,False,72800.0,3.0,Hybrid Remote,hour,83200.0,62400.0,"{\n ""lat"": 42.732535,\n ""lon"": -84.5555347\n}",TGFuc2luZywgTUk=,"Lansing, MI",26065.0,"Ingham, MI",29620.0,"Lansing-East Lansing, MI",26.0,Michigan,26065.0,"Ingham, MI",26065.0,"Ingham, MI",29620.0,"Lansing-East Lansing, MI",29620.0,"Lansing-East Lansing, MI",56.0,Administrative and Support and Waste Managemen...,561.0,Administrative and Support Services,5613.0,Employment Services,56131.0,Employment Placement Agencies and Executive Se...,561311.0,Employment Placement Agencies,ET3037E0C947A02404,Data Analysts,data analyst,"[\n ""KSQPGV2XZO8UMNCC49LK"",\n ""ES899BA440FA3...","[\n ""Detail Oriented"",\n ""Workflow Managemen...","[\n ""ES899BA440FA3441F22A"",\n ""KS1203K6FQ749...","[\n ""Workflow Management"",\n ""Acceptance Tes...",[],[],"[\n ""KSQPGV2XZO8UMNCC49LK"",\n ""KS1200H6XYN1C...","[\n ""Detail Oriented"",\n ""Microsoft Excel"",\...","[\n ""KS1200H6XYN1CR0G5NZ0"",\n ""KS1218L60PDVZ...","[\n ""Microsoft Excel"",\n ""Dashboard"",\n ""Ta...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""30.7101"",\n ""27.0501"",\n ""11.0701""\n]","[\n ""Data Analytics, General"",\n ""Statistics...","[\n ""30.71"",\n ""27.05"",\n ""11.07""\n]","[\n ""Data Analytics"",\n ""Statistics"",\n ""Co...","[\n ""30"",\n ""27"",\n ""11""\n]","[\n ""Multi/Interdisciplinary Studies"",\n ""Ma...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231113.0,Data / Data Mining Analyst,23111310.0,Data Analyst,2311.0,Data Analysis and Mathematics,23111310.0,Data Analyst,231113.0,Data / Data Mining Analyst,2311.0,Data Analysis and Mathematics,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,56.0,Administrative and Support and Waste Managemen...,561.0,Administrative and Support Services,5613.0,Employment Services,56131.0,Employment Placement Agencies and Executive Se...,561311.0,Employment Placement Agencies
72496,2e842ecdc031bdb4b8f8c2f724b5c51cdc7814eb,10/16/2024,2024-10-16 13:45:59.907 Z,0.0,8/16/2024,10/15/2024,NaN,"[\n ""Job Board""\n]","[\n ""maine.gov""\n]","[\n ""https://joblink.maine.gov/jobs/1114773""\n]",[],NaN,Data Analyst,Data Analyst\n\nat Consolidated Communications...,9/8/2024,23.0,98412363.0,Consolidated Communications Enterprise Service...,Consolidated Communications Enterprise Service...,False,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),7.0,NaN,False,NaN,0.0,[None],NaN,NaN,NaN,"{\n ""lat"": 44.8016128,\n ""lon"": -68.7712257\n}",QmFuZ29yLCBNRQ==,"Bangor, ME",23019.0,"Penobscot, ME",12620.0,"Bangor, ME",23.0,Maine,23019.0,"Penobscot, ME",23019.0,"Penobscot, ME",12620.0,"Bangor, ME",12620.0,"Bangor, ME",51.0,Information,517.0,Telecommunications,5178.0,All Other Telecommunications,51781.0,All Other Telecommunications,517810.0,All Other Telecommunications,ET3037E0C947A02404,Data Analysts,data analyst,"[\n ""KS13USA80NE38XJHA2TL"",\n ""KS1219774ZFQ6...","[\n ""Power BI"",\n ""Business Reporting"",\n ""...","[\n ""KS13USA80NE38XJHA2TL"",\n ""KS1219774ZFQ6...","[\n ""Power BI"",\n ""Business Reporting"",\n ""...",[],[],"[\n ""KS1203C6N9B52QGB4H67"",\n ""KS7G747655VG2...","[\n ""Research"",\n ""Prioritization"",\n ""Writ...","[\n ""KS13USA80NE38XJHA2TL"",\n ""KS125LS6N7WP4...","[\n ""Power BI"",\n ""Python (Programming Langu...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""52.0101"",\n ""52.0201"",\n ""11.0103"",\n ...","[\n ""Business/Commerce, General"",\n ""Busines...","[\n ""52.01"",\n ""52.02"",\n ""11.01"",\n ""11.0...","[\n ""Business/Commerce, General"",\n ""Busines...","[\n ""52"",\n ""52"",\n ""11"",\n ""11""\n]","[\n ""Business, Management, Marketing, and Rel...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231113.0,Data / Data Mining Analyst,23111310.0,Data Analyst,2311.0,Data Analysis and Mathematics,23111310.0,Data Analyst,231113.0,Data / Data Mining Analyst,2311.0,Data Analysis and Mathematics,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,51.0,Information,517.0,Telecommunications,5178.0,All Other Telecommunications,51781.0,All Other Telecommunications,517810.0,All Other Telecommunications
72497,733c12969489de888093ef22d09204dc0945148a,10/9/2024,2024-10-09 18:07:44.758 Z,0.0,8/16/2024,8/22/2024,6.0,"[\n ""Job Board""\n]","[\n ""dice.com""\n]","[\n ""https://www.dice.com/job-detail/8f1208f4...",[],NaN,Oracle Fusion Analytics Warehouse (FAW) HCM Lead,Oracle Fusion Analytics Warehouse (FAW) HCM Le...,8/22/2024,6.0,39411763.0,Lorven Technologies,"Lorven Technologies, Inc.",True,[\n 2\n],"[\n ""Bachelor's degree""\n]",2.0,Bachelor's degree,NaN,NaN,1.0,Full-time (> 32 hours),NaN,NaN,False,NaN,1.0,Remote,NaN,NaN,NaN,"{\n ""lat"": 32.7766642,\n ""lon"": -96.7969879\n}",RGFsbGFzLCBUWA==,"Dallas, TX",48113.0,"Dallas, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",48.0,Texas,48113.0,"Dallas, TX",48113.0,"Dallas, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",19100.0,"Dallas-Fort Worth-Arlington, TX",54.0,"Professional, Scientific, and Technical Services",541.0,"Professional, Scientific, and Technical Services",5415.0,Computer Systems Design and Related Services,54151.0,Computer Systems Design and Related Services,541512.0,Computer Systems Design Services,ET36323C71A36AB5BD,Oracle HCM Consultants,oracle fusion analytics warehouse faw hcm lead,"[\n ""KS122PM76DCYL9WC89Y7"",\n ""KS124DX6G31F5...","[\n ""Data Modeling"",\n ""Warehousing"",\n ""Co...","[\n ""KS122PM76DCYL9WC89Y7"",\n ""KS124DX6G31F5...","[\n ""Data Modeling"",\n ""Warehousing"",\n ""Da...",[],[],"[\n ""KS122556LMQ829GZCCRV"",\n ""KS1259D6L30YY...","[\n ""Communication"",\n ""Interpersonal Commun...","[\n ""KS1218L60PDVZX16NZT1"",\n ""ES4A15D4D2BD2...","[\n ""Dashboard"",\n ""Oracle Human Capital Man...",15-2051.01,Business Intelligence Analysts,15-2051.01,Business Intelligence Analysts,"[\n ""11.0701""\n]","[\n ""Computer Science""\n]","[\n ""11.07""\n]","[\n ""Computer Science""\n]","[\n ""11""\n]","[\n ""Computer and Information Sciences and Su...",15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,23.0,Information Technology and Computer Science,231010.0,Business Intelligence Analyst,23101012.0,Oracle Consultant / Analyst,2310.0,Business Intelligence,23101012.0,Oracle Consultant / Analyst,231010.0,Business Intelligence Analyst,2310.0,Business Intelligence,23.0,Information Technology and Computer Science,15-0000,Computer and Mathematical Occupations,15-2000,Mathematical Science Occupations,15-2050,Data Scientists,15-2051,Data Scientists,NaN,NaN,54.0,"Professional, Scientific, and Technical Services",541.0,"Professional, Scientific, and Technical Services",5415.0,Computer Systems Design and Related Services,54151.0,Computer Systems Design and Related Services,541512.0,Computer Systems Design Services

In [7]:
df.isnull().sum()

ID                        22
LAST_UPDATED_DATE         22
LAST_UPDATED_TIMESTAMP    22
DUPLICATES                22
POSTED                    22
                          ..
NAICS_2022_4_NAME         44
NAICS_2022_5              44
NAICS_2022_5_NAME         44
NAICS_2022_6              44
NAICS_2022_6_NAME         44
Length: 131, dtype: int64

In [8]:
df.describe()

,DUPLICATES,DURATION,MODELED_DURATION,COMPANY,MIN_EDULEVELS,MAX_EDULEVELS,EMPLOYMENT_TYPE,MIN_YEARS_EXPERIENCE,MAX_YEARS_EXPERIENCE,SALARY,REMOTE_TYPE,SALARY_TO,SALARY_FROM,COUNTY,MSA,STATE,COUNTY_OUTGOING,COUNTY_INCOMING,MSA_OUTGOING,MSA_INCOMING,NAICS2,NAICS3,NAICS4,NAICS5,NAICS6,LOT_CAREER_AREA,LOT_OCCUPATION,LOT_SPECIALIZED_OCCUPATION,LOT_OCCUPATION_GROUP,LOT_V6_SPECIALIZED_OCCUPATION,LOT_V6_OCCUPATION,LOT_V6_OCCUPATION_GROUP,LOT_V6_CAREER_AREA,NAICS_2022_2,NAICS_2022_3,NAICS_2022_4,NAICS_2022_5,NAICS_2022_6
count,72476.000000,45182.000000,53208.000000,7.245400e+04,72454.000000,16315.000000,72454.000000,49352.000000,8430.000000,30808.000000,72454.000000,32398.000000,32398.000000,72454.000000,68549.000000,72454.000000,72454.000000,72454.000000,68549.000000,68536.000000,72454.000000,72454.000000,72454.000000,72454.000000,72454.000000,72454.000000,72454.000000,7.245400e+04,72454.000000,7.245400e+04,72454.000000,72454.000000,72454.000000,72454.000000,72454.000000,72454.000000,72454.000000,72454.000000
mean,1.081627,22.322695,19.737615,3.702704e+07,31.482527,2.833834,1.058768,5.486444,3.773903,117953.755031,0.297168,136113.264060,94005.134977,28771.740732,29727.064640,28.634651,28771.740732,28773.186035,29727.064640,29732.803694,58.352555,587.864590,5883.121995,58834.317125,588345.683937,22.281158,223931.694096,2.239318e+07,2239.204475,2.239318e+07,223931.694096,2239.204475,22.281158,58.352555,587.864590,5883.121995,58834.317125,588345.683937
std,2.807512,14.359085,12.963769,3.015089e+07,44.747433,0.584028,0.286997,3.322241,2.576739,45133.878359,0.653550,60946.203597,40369.319080,16255.506450,11534.671425,16.219197,16255.506450,16253.655771,11534.671425,11531.673537,18.626415,186.259064,1864.093904,18642.971892,186431.744508,2.854360,28542.747473,2.854275e+06,285.424309,2.854275e+06,28542.747473,285.424309,2.854360,18.626415,186.259064,1864.093904,18642.971892,186431.744508
min,0.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000,1.000000,0.000000,0.000000,15860.000000,0.000000,10617.000000,10230.000000,1003.000000,10100.000000,1.000000,1003.000000,1003.000000,10100.000000,10100.000000,11.000000,111.000000,1111.000000,11115.000000,111150.000000,11.000000,111110.000000,1.111101e+07,1111.000000,1.111101e+07,111110.000000,1111.000000,11.000000,11.000000,111.000000,1111.000000,11115.000000,111150.000000
25%,0.000000,11.000000,10.000000,6.505993e+06,2.000000,3.000000,1.000000,3.000000,2.000000,84928.500000,0.000000,91002.500000,63565.000000,13067.000000,18180.000000,13.000000,13067.000000,13067.000000,18180.000000,18180.000000,52.000000,522.000000,5223.000000,52232.000000,522320.000000,23.000000,231010.000000,2.310101e+07,2310.000000,2.310101e+07,231010.000000,2310.000000,23.000000,52.000000,522.000000,5223.000000,52232.000000,522320.000000
50%,0.000000,18.000000,16.000000,3.761516e+07,2.000000,3.000000,1.000000,5.000000,3.000000,116300.000000,0.000000,131040.000000,88000.000000,29095.000000,31080.000000,29.000000,29095.000000,29095.000000,31080.000000,31080.000000,54.000000,541.000000,5415.000000,54151.000000,541519.000000,23.000000,231113.000000,2.311131e+07,2311.000000,2.311131e+07,231113.000000,2311.000000,23.000000,54.000000,541.000000,5415.000000,54151.000000,541519.000000
75%,1.000000,32.000000,28.000000,4.330689e+07,99.000000,3.000000,1.000000,8.000000,5.000000,145600.000000,0.000000,175300.000000,118000.000000,44007.000000,39580.000000,44.000000,44007.000000,44007.000000,39580.000000,39580.000000,56.000000,561.000000,5614.000000,56149.000000,561499.000000,23.000000,231113.000000,2.311131e+07,2311.000000,2.311131e+07,231113.000000,2311.000000,23.000000,56.000000,561.000000,5614.000000,56149.000000,561499.000000
max,100.000000,59.000000,59.000000,1.082365e+08,99.000000,4.000000,3.000000,15.000000,14.000000,500000.000000,3.000000,950000.000000,800000.000000,56999.000000,49780.000000,56.000000,56999.000000,56999.000000,49780.000000,49780.000000,99.000000,999.000000,9999.000000,99999.000000,999999.000000,27.000000,271211.000000,2.712111e+07,2712.000000,2.712111e+07,271211.000000,2712.000000,27.000000,99.000000,999.000000,9999.000000,99999.000000,999999.000000